# Generated by Django 5.2.4 on 2025-08-02 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero_piloto', models.IntegerField(default=None)),
                ('moto', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('id_volta', models.IntegerField(default=0)),
                ('horario_largada', models.TimeField(blank=True, null=True)),
                ('horario_chegada', models.TimeField(blank=True, null=True)),
                ('tempo_volta', models.DurationField(blank=True, null=True)),
                ('tempo_total', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero_piloto', models.IntegerField(default=None)),
                ('moto', models.CharField(default=None, max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='enduromcb.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrarChegada',
            fields=[
                ('id_volta', models.AutoField(primary_key=True, serialize=False)),
                ('horario_chegada', models.TimeField(blank=True, null=True)),
                ('numero_piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chegadas', to='enduromcb.piloto')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrarLargada',
            fields=[
                ('id_volta', models.AutoField(primary_key=True, serialize=False)),
                ('horario_largada', models.TimeField(blank=True, null=True)),
                ('numero_piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='largadas', to='enduromcb.piloto')),
            ],
        ),
    ]
