# Generated by Django 5.2.4 on 2025-08-02 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enduromcb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrarchegada',
            old_name='numero_piloto',
            new_name='piloto',
        ),
        migrations.RenameField(
            model_name='registrarlargada',
            old_name='numero_piloto',
            new_name='piloto',
        ),
        migrations.AlterField(
            model_name='piloto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilotos', to='enduromcb.categoria'),
        ),
        migrations.AlterField(
            model_name='piloto',
            name='moto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='piloto',
            name='numero_piloto',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='resultados',
            name='id_volta',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resultados',
            name='numero_piloto',
            field=models.IntegerField(),
        ),
    ]
