# Generated by Django 5.2.4 on 2025-08-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enduromcb', '0002_rename_numero_piloto_registrarchegada_piloto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piloto',
            name='moto',
            field=models.CharField(blank=True, default='####', max_length=100),
        ),
    ]
