# Generated by Django 5.2.4 on 2025-08-30 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enduromcb', '0003_alter_piloto_moto'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemLargada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.IntegerField(unique=True, verbose_name='Posição de Largada')),
                ('piloto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordem_largada', to='enduromcb.piloto', verbose_name='Piloto')),
            ],
            options={
                'verbose_name': 'Ordem de Largada',
                'verbose_name_plural': 'Ordens de Largada',
                'ordering': ['posicao'],
            },
        ),
    ]
