# Generated by Django 5.2.4 on 2025-09-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enduromcb', '0004_ordemlargada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoProva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_voltas', models.IntegerField(default=5, verbose_name='Número de Voltas')),
            ],
            options={
                'verbose_name': 'Configuração da Prova',
                'verbose_name_plural': 'Configurações da Prova',
            },
        ),
    ]
